# Permalinks
permalink:           pretty

# Setup
title:               Grit & Grid Search
tagline:             A Data Science Blog
url:                 http://Andrewjportal.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrew Portal
  url:               
  email:             andrewjportal@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Andrewjportal

# Formerly gems now plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
